### ISSUE TITLE
Minecraft Crash Issue | MC Bug

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#1329]
```
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 04.09.17 20:30
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.minecraft.client.particle.EffectRenderer.updateEffects(EffectRenderer.java:170)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:2252)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1100)
	at net.minecraft.client.Minecraft.run(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(Main.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.minecraft.client.particle.EffectRenderer.updateEffects(EffectRenderer.java:170)

-- Affected level --
Details:
	Level name: MpServer
	All players: 6 total; [EntityPlayerSP['Marco09MC'/90272754, l='MpServer', x=264,73, y=41,76, z=236,86], EntityOtherPlayerMP['scorpion3013'/90121913, l='MpServer', x=266,91, y=67,09, z=238,34], EntityOtherPlayerMP['pekepon56'/90301162, l='MpServer', x=265,50, y=41,00, z=239,50], EntityOtherPlayerMP['WistarWolf'/89942777, l='MpServer', x=283,03, y=47,50, z=248,69], EntityOtherPlayerMP['PrimeGuyYT'/90287622, l='MpServer', x=288,84, y=41,00, z=236,50], EntityOtherPlayerMP['Riley_RC'/90024376, l='MpServer', x=263,66, y=41,00, z=241,57]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 266,00,41,00,240,00 - World: (266,41,240), Chunk: (at 10,2,0 in 16,15; contains blocks 256,0,240 to 271,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 218435642 game time, 1000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 20 total; [EntityHorse['Horse'/90270817, l='MpServer', x=255,94, y=38,00, z=193,09], EntityOtherPlayerMP['pekepon56'/90301162, l='MpServer', x=265,50, y=41,00, z=239,50], EntityOtherPlayerMP['scorpion3013'/90121913, l='MpServer', x=266,91, y=67,09, z=238,34], EntityOtherPlayerMP['scorpion3013'/90121913, l='MpServer', x=273,06, y=66,00, z=246,00], EntityOtherPlayerMP['Riley_RC'/90024376, l='MpServer', x=234,53, y=51,50, z=260,78], EntityPlayerSP['Marco09MC'/90272754, l='MpServer', x=264,73, y=41,76, z=236,86], EntityOtherPlayerMP['WistarWolf'/89942777, l='MpServer', x=283,03, y=47,50, z=248,69], EntityOtherPlayerMP['Riley_RC'/90024376, l='MpServer', x=263,66, y=41,00, z=241,57], EntityOtherPlayerMP['PrimeGuyYT'/90287622, l='MpServer', x=289,25, y=41,00, z=244,09], EntityOtherPlayerMP['scorpion3013'/90121913, l='MpServer', x=266,91, y=67,09, z=238,34], EntityOtherPlayerMP['PrimeGuyYT'/90287622, l='MpServer', x=288,84, y=41,00, z=236,50], EntityOtherPlayerMP['WhyS0S3r10us'/90237633, l='MpServer', x=268,74, y=41,00, z=229,59], EntityOtherPlayerMP['WistarWolf'/89942777, l='MpServer', x=283,03, y=47,50, z=248,69], EntityOtherPlayerMP['PrimeGuyYT'/90287622, l='MpServer', x=288,84, y=41,00, z=236,50], EntityOtherPlayerMP['Riley_RC'/90024376, l='MpServer', x=234,50, y=46,00, z=256,28], EntityOtherPlayerMP['_MyKnxck_'/90150015, l='MpServer', x=289,34, y=48,00, z=274,19], EntityOtherPlayerMP['Riley_RC'/90024376, l='MpServer', x=263,66, y=41,00, z=241,57], EntityOtherPlayerMP['WistarWolf'/89942777, l='MpServer', x=271,50, y=66,63, z=248,22], EntityOtherPlayerMP['pekepon56'/90301162, l='MpServer', x=265,50, y=41,00, z=239,50], EntityOtherPlayerMP['Riley_RC'/90024376, l='MpServer', x=234,53, y=51,50, z=260,84]]
	Retry entities: 0 total; []
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2675)
	at net.minecraft.client.Minecraft.run(Minecraft.java:413)
	at net.minecraft.client.main.Main.main(Main.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 720858904 bytes (687 MB) / 1788870656 bytes (1706 MB) up to 3814195200 bytes (3637 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forgeSrc-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
MixinLoader (unknown)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 384.76' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.5.0 NVIDIA 384.76, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor 
```

**Comment by Marco-MC** [comment]
Fixed.

Replaced
```
public void updateEffects()
    {
        for (int i = 0; i < 4; ++i)
        {
            this.updateEffectLayer(i);
        }

        List<EntityParticleEmitter> list = Lists.<EntityParticleEmitter>newArrayList();

        for (EntityParticleEmitter entityparticleemitter : this.particleEmitters)
        {
            entityparticleemitter.onUpdate();

            if (entityparticleemitter.isDead)
            {
                list.add(entityparticleemitter);
            }
        }

        this.particleEmitters.removeAll(list);
    }
```
to
```
/**
     * @author Mojang
     * @author Marco
     */
    @Overwrite
    public void updateEffects() {
        try{
            for(int i = 0; i < 4; ++i)
                this.updateEffectLayer(i);

            for(final Iterator<EntityParticleEmitter> it = this.particleEmitters.iterator(); it.hasNext(); ) {
                final EntityParticleEmitter entityParticleEmitter = it.next();

                entityParticleEmitter.onUpdate();

                if(entityParticleEmitter.isDead)
                    it.remove();
            }
        }catch(final ConcurrentModificationException e) {
            System.err.println("(EffectRenderer:updateEffects) " + e.getClass().getName() + ": " + e.getMessage());
        }
    }
```
