### ISSUE TITLE
ShadersMods crash

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#1958]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ItemPatchingLoader (ItemPhysic Lite 1.3 mc1.8.9.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 11.03.18 12:41
Description: Unexpected error

java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.EntityRenderer.func_78479_a(FI)V from class shadersmod.client.ShadersRender
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:278)
	at shadersmod.client.Shaders.beginRender(Shaders.java:4087)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1559)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1370)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:278)
	at shadersmod.client.Shaders.beginRender(Shaders.java:4087)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1559)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['shanksie'/179, l='MpServer', x=428,62, y=67,00, z=-540,04]]
	Chunk stats: MultiplayerChunkCache: 279, 279
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 12,00,64,00,220,00 - World: (12,64,220), Chunk: (at 12,4,12 in 0,13; contains blocks 0,0,208 to 15,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 366938 game time, 366938 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 44 total; [EntityChicken['Chicken'/192, l='MpServer', x=461,22, y=71,00, z=-567,53], EntityChicken['Chicken'/193, l='MpServer', x=457,53, y=71,00, z=-553,69], EntityChicken['Chicken'/194, l='MpServer', x=458,22, y=67,59, z=-559,38], EntityItem['item.item.egg'/195, l='MpServer', x=455,34, y=70,00, z=-558,59], EntityBat['Bat'/196, l='MpServer', x=377,25, y=31,10, z=-543,38], EntityBat['Bat'/197, l='MpServer', x=377,25, y=30,10, z=-540,25], EntitySkeleton['Skeleton'/198, l='MpServer', x=372,69, y=30,00, z=-516,13], EntityItem['item.tile.cactus'/199, l='MpServer', x=368,13, y=66,00, z=-525,56], EntityItem['item.tile.cactus'/200, l='MpServer', x=370,50, y=68,00, z=-525,56], EntitySpider['Spider'/201, l='MpServer', x=379,50, y=12,00, z=-509,50], EntitySpider['Spider'/202, l='MpServer', x=377,50, y=12,00, z=-509,50], EntitySkeleton['Skeleton'/203, l='MpServer', x=382,50, y=12,00, z=-511,50], EntityChicken['Chicken'/204, l='MpServer', x=370,56, y=65,00, z=-562,38], EntitySkeleton['Skeleton'/205, l='MpServer', x=361,56, y=14,00, z=-531,94], EntityZombie['Zombie'/206, l='MpServer', x=359,97, y=41,00, z=-534,59], EntityZombie['Zombie'/207, l='MpServer', x=358,50, y=41,00, z=-532,50], EntityZombie['Zombie'/208, l='MpServer', x=426,50, y=30,00, z=-477,50], EntityZombie['Zombie'/209, l='MpServer', x=365,50, y=27,00, z=-519,50], EntitySkeleton['Skeleton'/210, l='MpServer', x=351,69, y=17,00, z=-522,09], EntitySkeleton['Skeleton'/211, l='MpServer', x=354,28, y=16,00, z=-516,63], EntityZombie['Zombie'/212, l='MpServer', x=353,28, y=17,00, z=-519,91], EntitySkeleton['Skeleton'/213, l='MpServer', x=352,44, y=17,00, z=-523,00], EntitySpider['Spider'/214, l='MpServer', x=355,50, y=41,00, z=-545,50], EntityChicken['Chicken'/215, l='MpServer', x=495,69, y=77,00, z=-519,41], EntityZombie['Zombie'/216, l='MpServer', x=373,50, y=34,00, z=-591,50], EntityEnderman['Enderman'/217, l='MpServer', x=375,50, y=36,00, z=-588,50], EntitySpider['Spider'/218, l='MpServer', x=358,50, y=28,00, z=-497,03], EntityChicken['Chicken'/219, l='MpServer', x=503,44, y=75,00, z=-510,56], EntityCreeper['Creeper'/220, l='MpServer', x=358,44, y=37,00, z=-589,38], EntitySkeleton['Skeleton'/222, l='MpServer', x=503,47, y=19,00, z=-485,56], EntityRabbit['Rabbit'/233, l='MpServer', x=358,19, y=64,00, z=-612,81], EntityRabbit['Rabbit'/234, l='MpServer', x=356,50, y=64,00, z=-612,50], EntityRabbit['Rabbit'/235, l='MpServer', x=356,16, y=64,00, z=-611,78], EntityPlayerSP['shanksie'/179, l='MpServer', x=428,62, y=67,00, z=-540,04], EntityCreeper['Creeper'/181, l='MpServer', x=443,63, y=56,00, z=-529,78], EntitySkeleton['Skeleton'/182, l='MpServer', x=400,06, y=28,00, z=-551,44], EntityCreeper['Creeper'/184, l='MpServer', x=423,03, y=12,00, z=-511,53], EntitySkeleton['Skeleton'/185, l='MpServer', x=384,50, y=12,00, z=-512,50], EntityChicken['Chicken'/186, l='MpServer', x=386,97, y=65,00, z=-554,47], EntityChicken['Chicken'/187, l='MpServer', x=384,50, y=65,00, z=-553,50], EntityChicken['Chicken'/188, l='MpServer', x=388,50, y=65,00, z=-554,50], EntityItem['item.item.egg'/189, l='MpServer', x=384,53, y=65,00, z=-553,09], EntityChicken['Chicken'/190, l='MpServer', x=438,59, y=67,00, z=-570,44], EntityItem['item.item.egg'/191, l='MpServer', x=439,41, y=67,00, z=-569,53]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:412)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 16x AMD Ryzen 7 1800X Eight-Core Processor 
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1196045056 bytes (1140 MB) / 2852126720 bytes (2720 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_I3 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJAAAA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJAAAA	itemphysic{1.3.0} [ItemPhysic] (minecraft.jar) 
	Loaded coremods (and transformers): 
ItemPatchingLoader (ItemPhysic Lite 1.3 mc1.8.9.jar)
  com.creativemd.itemphysic.ItemTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 390.77' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 390.77, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: PureBDcraft 128x MC18.zip
	Current Language: English (US)
	Profiler Position: root.gameRenderer.level.shadow camera
	CPU: 16x AMD Ryzen 7 1800X Eight-Core Processor 
	OptiFine Version: OptiFine_1.8.9_HD_U_I3
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Chocapic13 V7 Extreme RC1.zip
	OpenGlVersion: 4.6.0 NVIDIA 390.77
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by Marco-MC** [comment]
Fixed.
![2018-03-11_12 58 11](https://user-images.githubusercontent.com/12410754/37252991-df099632-252b-11e8-862b-33218c69136e.png)
