### ISSUE TITLE
Crash-Report (.give) (Code mehrfach schnell hintereinander eingefügt)

### ISSUE THREAD

**Issue by RealFantaCoke** [CCBlueX/LiquidBounce1.8-Issues#1966]
java.lang.StringIndexOutOfBoundsException: String index out of range: 144
	at java.lang.String.substring(Unknown Source)
	at net.minecraft.client.gui.GuiTextField.func_146191_b(SourceFile:103)
	at net.minecraft.client.gui.GuiTextField.func_146201_a(SourceFile:257)
	at net.minecraft.client.gui.GuiChat.func_73869_a(GuiChat.java:102)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:578)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:534)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Marco-MC** [comment]
Es erscheint mir, dass Minecraft ein Problem damit hat, wenn man die TextField Length auf `Integer.MAX_VALUE` setzt, deshalb habe ich das Länge jetzt auf `10000` beschränkt bei `.` Commands.

Ebenfalls kann ich diesen Fehler nicht reproduzieren, somit kann ich auch nicht den genauen Grund dafür finden.
Es liegt an an den drei `String.substring` aufrufen, von der `writeText` Method in der Klasse `GuiTextField`.
