### ISSUE TITLE
CustomHUD broken config add error handling

### ISSUE THREAD

**Issue by Marco-MC** [CCBlueX/LiquidBounce1.8-Issues#1993]
```
java.lang.ClassCastException: Cannot cast com.google.gson.JsonPrimitive to com.google.gson.JsonArray
	at java.lang.Class.cast(Class.java:3361)
	at com.google.gson.Gson.fromJson(Gson.java:690)
	at META-INF.byCCBlueX.lll111l1l.<init>(???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????)
	at META-INF.byCCBlueX.ll1llll.lllll(?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????)
	at META-INF.byCCBlueX.l1.l(?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????)
	at net.minecraft.client.Minecraft.handler$startGame$zzp000(Minecraft.java:3166)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Marco-MC** [comment]
Added
