### ISSUE TITLE
Cannot reload scripts & crash while .reload

### ISSUE THREAD

**Issue by yKsenomorf** [CCBlueX/LiquidBounce1.8-Issues#2714]
`[INFO] Caused by: java.lang.ClassCastException: Cannot cast jdk.nashorn.internal.runtime.Undefined to jdk.nashorn.api.scripting.ScriptObjectMirror
[INFO] 	at java.lang.invoke.MethodHandleImpl.newClassCastException(Unknown Source) ~[?:1.8.0_171]
[INFO] 	at java.lang.invoke.MethodHandleImpl.castReference(Unknown Source) ~[?:1.8.0_171]
[INFO] 	at jdk.nashorn.internal.scripts.Script$Recompilation$8$300$\^eval\_.onEnable(<eval>:19) ~[?:?]
[INFO] 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(FumeObfuscator:637) ~[ScriptFunctionData.class:?]
[INFO] 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(FumeObfuscator:494) ~[ScriptFunction.class:?]
[INFO] 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(FumeObfuscator:393) ~[ScriptRuntime.class:?]
[INFO] 	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(FumeObfuscator:199) ~[ScriptObjectMirror.class:?]
[INFO] 	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(FumeObfuscator:386) ~[NashornScriptEngine.class:?]
[INFO] 	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(FumeObfuscator:190) ~[NashornScriptEngine.class:?]
[INFO] 	at META-INF.byCCBlueX.LiquidBounce.llll1l1l1.callFunction(FumeObfuscator:117) ~[llll1l1l1.class:?]
[INFO] 	at META-INF.byCCBlueX.LiquidBounce.llll1l1l1.onEnable(FumeObfuscator:93) ~[llll1l1l1.class:?]
[INFO] 	at META-INF.byCCBlueX.LiquidBounce.llll1l1l1.reloadScript(FumeObfuscator:76) ~[llll1l1l1.class:?]
[INFO] 	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_171]
[INFO] 	at META-INF.byCCBlueX.LiquidBounce.llll11l.execute() ~[llll11l.class:?]
[INFO] 	at META-INF.byCCBlueX.LiquidBounce.l1l111.l() ~[l1l111.class:?]
[INFO] 	at net.minecraft.client.gui.GuiScreen.handler$messageSend$zbd000(GuiScreen.java:851) ~[axu.class:?]
[INFO] 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java) ~[axu.class:?]
[INFO] 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:437) ~[axu.class:?]
[INFO] 	at net.minecraft.client.gui.GuiChat.func_73869_a(GuiChat.java:111) ~[awv.class:?]
[INFO] 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:578) ~[axu.class:?]
[INFO] 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:534) ~[axu.class:?]
[INFO] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674) ~[ave.class:?]
[INFO] 	... 9 more`

**Comment by yKsenomorf** [comment]
Solved
