### ISSUE TITLE
[BUG] This crash the client

### ISSUE THREAD

**Issue by Leejames2305** [CCBlueX/LiquidBounce1.8-Issues#3278]
https://imgur.com/5uU69Fz

**Comment by Leejames2305** [comment]
When I disconnect or reconnect from a server , this spammed the logs and cause client to crash .

**Comment by Marco09MC** [comment]
We need more details about this issue like where (singleplayer (world?), multiplayer (server ip?)), entire log and I don't think that liquidbounce is the reason... much more just a normal minecraft/forge bug.

**Comment by Leejames2305** [comment]
This only happen in multiplayer no matter which server I disconnect / reconnect from . It happens 1 out of 5 times . 
Whenever this bug happen , it freeze the client and Liquidlauncher and I can't even see the whole logs as it spam 100 logs per second . What can I only do is force close both and reopen the launcher .

**Comment by yorik100** [comment]
When I press reconnect I sometimes crash so idk if it's the problem

**Comment by SenkJu** [comment]
Do you use any other mods in addition to LiquidBounce?

**Comment by Leejames2305** [comment]
Just Optifine only

**Comment by yorik100** [comment]
> 
> 
> Do you use any other mods in addition to LiquidBounce?

It causes crashes because sometimes it uses too much the processor, the crashes never happen on my god computer

**Comment by Leejames2305** [comment]
Yeah , High end pc won't have this problem but for my I5-6200U , it can't handle it .

**Comment by Leejames2305** [comment]
Ok , after some testing , I found out that this will mostly happen on tree.ac

**Comment by Leejames2305** [comment]
Logs in B68

`[00:30:26] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
at net.minecraft.util.Util.func_181617_a(Util.java:20) [g.class:?]
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1014) [ave.class:?]
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
at net.minecraft.client.network.NetHandlerPlayClient.func_147284_a(NetHandlerPlayClient.java:468) ~[bcy.class:?]
at net.minecraft.network.play.server.S1CPacketEntityMetadata.func_148833_a(SourceFile:41) ~[hk.class:?]
at net.minecraft.network.play.server.S1CPacketEntityMetadata.func_148833_a(SourceFile:11) ~[hk.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[fh$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
at net.minecraft.util.Util.func_181617_a(Util.java:19) ~[g.class:?]
... 9 more`

**Comment by Leejames2305** [comment]
@Marco09MC So , after testing it for many hours , I came with a conclusion that this will mostly happen when the server is very laggy and you try to disconnect when the server isn't responding at all .
