### ISSUE TITLE
[FEATURE] Tab Completion for commands

### ISSUE THREAD

**Issue by NurMarvin** [CCBlueX/LiquidBounce1.8-Issues#3372]
**Describe your feature request.**
Add tab completion to LiquidBounce commands as well as adding a semi-opaque suggestion based on the provided arguments.

**Additional context**
I will add this myself, I just create this issue for milestone tracking, so consider this a feature to expect in one of the next few builds.

**Comment by NurMarvin** [comment]
Added
![P89U9spRAl](https://user-images.githubusercontent.com/17235016/71949514-1d24cc00-31d4-11ea-941e-fdbd6b52d37f.gif)

**Comment by yKsenomorf** [comment]
Semi-opaque arguments suggestion was added in 1.13, I think
You have to move the code from it

**Comment by kawaiinekololis** [comment]
https://axolotl.vip/ZAbetTQB.mp4?key=PVc8o9XEbvPogT

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.ArrayList.rangeCheck(ArrayList.java:657)
    at java.util.ArrayList.get(ArrayList.java:433)
    at net.minecraft.client.gui.GuiChat.autocompletePlayerNames(GuiChat.java:247)
    at net.minecraft.client.gui.GuiChat.keyTyped(GuiChat.java:91)
    at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:659)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:609)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1784)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1100)
    at net.minecraft.client.Minecraft.run(Minecraft.java:384)
    at net.minecraft.client.main.Main.main(Main.java:116)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
    at GradleStart.main(GradleStart.java:26)
```

one bug left

**Comment by xHackerBey-Egemen** [comment]
looks so useful

**Comment by Teals53** [comment]
@kawaiinekololis which test server r u playing ?
