### ISSUE TITLE
[BUG] Crash issue: Skull skinprotect NPE

### ISSUE THREAD

**Issue by kawaiinekololis** [CCBlueX/LiquidBounce1.8-Issues#3560]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (MemoryFix-0.3.jar)
  TransformerLoader (LiquidBounce1.8.9.jar)
  TLSkinCapeHookLoader (tlskincape_1.8.9-1.4.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 21/02/20 05:02
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at net.minecraft.client.resources.SkinManager.handler$injectSkinProtect$zcg000(SourceFile:525)
	at net.minecraft.client.resources.SkinManager.func_152788_a(SourceFile)
	at net.minecraft.client.renderer.tileentity.TileEntitySkullRenderer.func_180543_a(SourceFile:76)
	at net.minecraft.client.renderer.tileentity.TileEntitySkullRenderer.func_180535_a(SourceFile:38)
	at net.minecraft.client.renderer.tileentity.TileEntitySkullRenderer.func_180535_a(SourceFile:21)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:182)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:143)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:946)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1763)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1580)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1372)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.resources.SkinManager.handler$injectSkinProtect$zcg000(SourceFile:525)
	at net.minecraft.client.resources.SkinManager.func_152788_a(SourceFile)
	at net.minecraft.client.renderer.tileentity.TileEntitySkullRenderer.func_180543_a(SourceFile:76)
	at net.minecraft.client.renderer.tileentity.TileEntitySkullRenderer.func_180535_a(SourceFile:38)
	at net.minecraft.client.renderer.tileentity.TileEntitySkullRenderer.func_180535_a(SourceFile:21)

-- Block Entity Details --
Details:
	Name: Skull // net.minecraft.tileentity.TileEntitySkull
	Block type: ID #144 (tile.skull // net.minecraft.block.BlockSkull)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-3,72,-61), Chunk: (at 13,4,3 in -1,-4; contains blocks -16,0,-64 to -1,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #144 (tile.skull // net.minecraft.block.BlockSkull)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:182)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:143)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:946)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1763)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1580)

-- Affected level --
Details:
	Level name: MpServer
	All players: 3 total; [EntityPlayerSP['CEO_OF_HDR'/296625, l='MpServer', x=-2.00, y=70.00, z=-42.00], EntityOtherPlayerMP['FMLsSToiSenpaosS'/9555, l='MpServer', x=-0.72, y=70.00, z=-39.09], EntityOtherPlayerMP['De_GaMing_2020'/9565, l='MpServer', x=-0.41, y=70.00, z=-42.13]]
	Chunk stats: MultiplayerChunkCache: 20, 20
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -2.00,70.00,-42.00 - World: (-2,70,-42), Chunk: (at 14,4,6 in -1,-3; contains blocks -16,0,-48 to -1,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1569916294 game time, 1464000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 13 total; [EntityArmorStand['§6§lServer KitPVP Phiên B?n 4.2'/1, l='MpServer', x=-1.53, y=72.72, z=-36.31], EntityArmorStand['§fNâng c?p §6§lVIP§f dùng l?nh §a/shop'/2, l='MpServer', x=-1.53, y=72.47, z=-36.31], EntityArmorStand['§e§lH??ng d?n cách ch?i'/3, l='MpServer', x=-1.53, y=72.22, z=-36.31], EntityArmorStand['§fCh?n Kit và ?i th?ng phía tr??c chi?n ??u t? do'/4, l='MpServer', x=-1.53, y=71.97, z=-36.31], EntityArmorStand['§fHo?c dùng g?y g?i l?i m?i thánh ??u 1vs1'/5, l='MpServer', x=-1.53, y=71.72, z=-36.31], EntityArmorStand['§f2 bên dùng g?y nh?p chu?t ph?i vào nhau'/6, l='MpServer', x=-1.53, y=71.47, z=-36.31], EntityArmorStand['§fcu?c thách ??u s? di?n ra và b?n ph?i tiêu di?t ??i ph??ng'/7, l='MpServer', x=-1.53, y=71.22, z=-36.31], EntityArmorStand['§fGi?t nhi?u ng??i s? giúp b?n nhanh ch?ng nâng c?p rank'/8, l='MpServer', x=-1.53, y=70.97, z=-36.31], EntityPlayerSP['CEO_OF_HDR'/296625, l='MpServer', x=-2.00, y=70.00, z=-42.00], EntityOtherPlayerMP['FMLsSToiSenpaosS'/9555, l='MpServer', x=-0.72, y=70.00, z=-39.09], EntityOtherPlayerMP['FMLsSToiSenpaosS'/9555, l='MpServer', x=-0.72, y=70.00, z=-39.09], EntityOtherPlayerMP['De_GaMing_2020'/9565, l='MpServer', x=-0.41, y=70.00, z=-42.13], EntityOtherPlayerMP['De_GaMing_2020'/9565, l='MpServer', x=-0.41, y=70.00, z=-42.13]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.15-SNAPSHOT:e6b0d43:1479) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2583886328 bytes (2464 MB) / 3140747264 bytes (2995 MB) up to 3140747264 bytes (2995 MB)
	JVM Flags: 28 total; -Xmn128M -Xmx3987M -XX:+UseConcMarkSweepGC -Xmx3G -Xms3G -Xmn768m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_L5 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	memoryfix{0.3} [MemoryFix] (MemoryFix-0.3.jar) 
	UCHIJA	tlauncher_custom_cape_skin{1.4} [TLSkinCape] (tlskincape_1.8.9-1.4.jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (MemoryFix-0.3.jar)
  io.prplz.memoryfix.ClassTransformer
TransformerLoader (LiquidBounce1.8.9.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
TLSkinCapeHookLoader (tlskincape_1.8.9-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4821' Renderer: 'Intel(R) HD Graphics 520'
	Launched Version: Forge 1.8.9
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.4.0 - Build 21.20.16.4821, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: AMAZING_FAITHFUL_EDIT
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 5
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 21.20.16.4821
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4
```

**Comment by superblaubeere27** [comment]
Fixed.
