### ISSUE TITLE
[BUG]Replay Mod

### ISSUE THREAD

**Issue by ChineseCookie** [CCBlueX/LiquidBounce1.8-Issues#3869]
2020-07-18 18:46:10,423 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream

2020-07-18 18:46:10,425 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream

[18:46:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker

[18:46:10] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker

[18:46:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker

[18:46:10] [main/INFO] [FML]: Forge Mod Loader version 11.15.1.2318 for Minecraft 1.8.9 loading

[18:46:10] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_191, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jdk1.8.0_191\jre

[18:46:10] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from LiquidBounce-b73.jar

[18:46:10] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.8.9_HD_U_L5.jar

[18:46:10] [main/INFO] [FML]: Loading tweaker com.replaymod.core.tweaker.ReplayModTweaker from replaymod-1.8.9-2.4.0.jar

[18:46:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker

[18:46:10] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker

[18:46:10] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.10 Source=file:/D:/Minecraft/Client/.minecraft/mods/LiquidBounce-b73.jar Service=LaunchWrapper Env=CLIENT

[18:46:10] [main/WARN] [FML]: The coremod net.ccbluex.liquidbounce.injection.forge.TransformerLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft

[18:46:10] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker

[18:46:10] [main/INFO] [LaunchWrapper]: Loading tweak class name com.replaymod.core.tweaker.ReplayModTweaker

[18:46:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker

[18:46:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker

[18:46:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker

[18:46:10] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker

[18:46:10] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions

[18:46:10] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader

[18:46:10] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer

[18:46:10] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: D:\Minecraft\Client\.minecraft\mods\OptiFine_1.8.9_HD_U_L5.jar

[18:46:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper

[18:46:12] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557

[18:46:12] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc

[18:46:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper

[18:46:12] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker

[18:46:12] [main/INFO] [mixin]: Compatibility level set to JAVA_8

[18:46:12] [main/ERROR] [mixin]: Mixin config liquidbounce.forge.mixins.json does not specify "minVersion" property

2020-07-18 18:46:12,925 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream

2020-07-18 18:46:12,947 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream

2020-07-18 18:46:12,962 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream

[18:46:12] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@d78795

[18:46:13] [main/INFO] [LaunchWrapper]: Calling tweak class com.replaymod.core.tweaker.ReplayModTweaker

[18:46:13] [main/WARN] [FML]: The coremod com.replaymod.core.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft

[18:46:13] [main/INFO] [STDOUT]: [com.replaymod.extras.modcore.ModCoreInstaller:fetchString:255]: Fetching https://api.sk1er.club/modcore_versions

[18:46:15] [main/INFO] [STDOUT]: [com.replaymod.extras.modcore.ModCoreInstaller:initialize:134]: No ModCore target for 1.8.9_forge. This in fine, unless you're specifically looking for ModCore.

[18:46:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker

[18:46:15] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker

[18:46:15] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker

[18:46:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker

[18:46:15] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker

[18:46:15] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments

[18:46:17] [main/INFO] [mixin]: A re-entrant transformer '$wrapper.net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer' was detected and will no longer process meta class data

[18:46:17] [main/WARN] [mixin]: Error loading class: net/minecraft/client/renderer/WorldRenderer$LocalRenderInformationContainer (java.lang.ClassNotFoundException: The specified class 'net.minecraft.client.renderer.WorldRenderer$LocalRenderInformationContainer' was not found)

[18:46:17] [main/WARN] [mixin]: @Mixin target net.minecraft.client.renderer.WorldRenderer$LocalRenderInformationContainer was not found mixins.render.blend.replaymod.json:ContainerLocalRenderInformationAccessor

[18:46:17] [main/WARN] [mixin]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: The specified class 'shadersmod.client.ShadersRender' was not found)

[18:46:17] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}

[18:46:19] [Client thread/INFO]: Setting user: LiquidSlowly

[18:46:24] [Client thread/INFO] [Config]: [OptiFine] *** Reflector Forge ***

[18:46:24] [Client thread/INFO] [Config]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient

[18:46:24] [Client thread/WARN] [mixin]: Method overwrite conflict for getHandler in mixins.render.replaymod.json:MixinCamera, previously written by com.replaymod.render.mixin.Mixin_CubicRotation. Skipping method.

[18:46:26] [Client thread/FATAL] [mixin]: Mixin apply failed mixins.replay.replaymod.json:MixinRenderLivingBase -> net.minecraft.client.renderer.entity.RendererLivingEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/client/renderer/entity/RendererLivingEntity::redirect$replayModReplay_shouldInvisibleNotBeRendered$zek000 with priority 1000 cannot inject into net/minecraft/client/renderer/entity/RendererLivingEntity::func_77036_a(Lnet/minecraft/entity/EntityLivingBase;FFFFFF)V merged by net.ccbluex.liquidbounce.injection.forge.mixins.render.MixinRendererLivingEntity with priority 1000

org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/client/renderer/entity/RendererLivingEntity::redirect$replayModReplay_shouldInvisibleNotBeRendered$zek000 with priority 1000 cannot inject into net/minecraft/client/renderer/entity/RendererLivingEntity::func_77036_a(Lnet/minecraft/entity/EntityLivingBase;FFFFFF)V merged by net.ccbluex.liquidbounce.injection.forge.mixins.render.MixinRendererLivingEntity with priority 1000

	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:229) ~[LiquidBounce-b73.jar:?]

	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:176) ~[LiquidBounce-b73.jar:?]

	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:257) ~[LiquidBounce-b73.jar:?]

	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1186) ~[LiquidBounce-b73.jar:?]

	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:900) ~[LiquidBounce-b73.jar:?]

	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:304) ~[LiquidBounce-b73.jar:?]

	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267) ~[LiquidBounce-b73.jar:?]

	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[LiquidBounce-b73.jar:?]

	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) [LiquidBounce-b73.jar:?]

	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) [LiquidBounce-b73.jar:?]

	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) [LiquidBounce-b73.jar:?]

	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [LiquidBounce-b73.jar:?]

	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]

	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_191]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_191]

	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:348) [Reflector.class:?]

	at net.optifine.reflect.ReflectorForge.<clinit>(ReflectorForge.java:32) [ReflectorForge.class:?]

	at Config.initGameSettings(Config.java:212) [Config.class:?]

	at net.minecraft.client.settings.GameSettings.<init>(GameSettings.java:343) [avh.class:?]

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:395) [ave.class:?]

	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329) [ave.class:?]

	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.replay.replaymod.json:MixinRenderLivingBase] from phase [DEFAULT] in config [mixins.replay.replaymod.json] FAILED during APPLY

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:348)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.optifine.reflect.ReflectorForge.<clinit>(ReflectorForge.java:32)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at Config.initGameSettings(Config.java:212)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.settings.GameSettings.<init>(GameSettings.java:343)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:395)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.main.Main.main(SourceFile:124)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.reflect.Method.invoke(Method.java:498)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

[18:46:26] [Client thread/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/client/renderer/entity/RendererLivingEntity::redirect$replayModReplay_shouldInvisibleNotBeRendered$zek000 with priority 1000 cannot inject into net/minecraft/client/renderer/entity/RendererLivingEntity::func_77036_a(Lnet/minecraft/entity/EntityLivingBase;FFFFFF)V merged by net.ccbluex.liquidbounce.injection.forge.mixins.render.MixinRendererLivingEntity with priority 1000

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:229)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:176)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:257)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1186)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:900)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:304)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 18 more

[18:46:26] [Client thread/ERROR] [LaunchWrapper]: Unable to launch

java.lang.reflect.InvocationTargetException

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.optifine.reflect.Reflector

	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:137) ~[b.class:?]

	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:53) ~[b.class:?]

	at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:414) ~[b.class:?]

	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:333) ~[ave.class:?]

	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]

	... 6 more

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)

[18:46:26] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Exception in thread "Client thread"

**Comment by lolmc1982** [comment]
Liquidbounce not working with a replay mod because have some problem

**Comment by Litely1222** [comment]
> Liquidbounce not working with a replay mod because have some problem
