### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ImChinaNB** [CCBlueX/LiquidBounce1.8-Issues#3902]
**Describe the bug**
Game crashes with any scripts that uses Core as lib.
kotlin.UninitializedPropertyAccessException: lateinit property scriptName has not been initialized
	at net.ccbluex.liquidbounce.script.Script.getScriptName(Script.kt:39)
	at net.ccbluex.liquidbounce.ui.client.GuiUnsignedScripts$initGui$text$1.invoke(GuiUnsignedScripts.kt:24)
	at net.ccbluex.liquidbounce.ui.client.GuiUnsignedScripts$initGui$text$1.invoke(GuiUnsignedScripts.kt:19)
	at kotlin.text.StringsKt__StringBuilderKt.appendElement(StringBuilder.kt:58)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2313)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:2330)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:2329)
	at net.ccbluex.liquidbounce.ui.client.GuiUnsignedScripts.initGui(GuiUnsignedScripts.kt:24)
	at net.ccbluex.liquidbounce.injection.backend.utils.GuiScreenWrapper.func_73866_w_(GuiScreenWrapper.kt:16)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:502)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:930)
	at net.ccbluex.liquidbounce.injection.backend.MinecraftImpl.displayGuiScreen(MinecraftImpl.kt:95)
	at net.minecraft.client.Minecraft.handler$afterMainScreen$zzf000(Minecraft.java:3213)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:505)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.ccbluex.liquidbounce.script.Script.getScriptName(Script.kt:39)
	at net.ccbluex.liquidbounce.ui.client.GuiUnsignedScripts$initGui$text$1.invoke(GuiUnsignedScripts.kt:24)
	at net.ccbluex.liquidbounce.ui.client.GuiUnsignedScripts$initGui$text$1.invoke(GuiUnsignedScripts.kt:19)
	at kotlin.text.StringsKt__StringBuilderKt.appendElement(StringBuilder.kt:58)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2313)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:2330)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:2329)
	at net.ccbluex.liquidbounce.ui.client.GuiUnsignedScripts.initGui(GuiUnsignedScripts.kt:24)
	at net.ccbluex.liquidbounce.injection.backend.utils.GuiScreenWrapper.func_73866_w_(GuiScreenWrapper.kt:16)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:502)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:930)
	at net.ccbluex.liquidbounce.injection.backend.MinecraftImpl.displayGuiScreen(MinecraftImpl.kt:95)
	at net.minecraft.client.Minecraft.handler$afterMainScreen$zzf000(Minecraft.java:3213)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:505)

Lastet Nightly build.

**Comment by ImChinaNB** [comment]
sry i typo I means crashes with a signed script and any unsigned script

**Comment by lolmc1982** [comment]
Lastest build have some problem about script
It will get fixed soon
